### ISSUE TITLE
Use redis.exist? in session_exists?

### ISSUE THREAD

**Issue by sohymg** [roidrage/redis-session-store#120]
https://github.com/roidrage/redis-session-store/blob/master/lib/redis-session-store.rb#L70

Redis warns:
> Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/app/vendor/bundle/ruby/2.6.0/gems/redis-session-store-0.11.1/lib/redis-session-store.rb:70:in `session_exists?

**Comment by Jesterovskiy** [comment]
https://github.com/roidrage/redis-session-store/pull/119
