### ISSUE TITLE
Is redis gem v5 actually a blocker?

### ISSUE THREAD

**Issue by leastbad** [roidrage/redis-session-store#135]
Hey gang,

https://github.com/roidrage/redis-session-store/blob/e9a7d80c937c04896afe155bfc02e299e23fccf8/redis-session-store.gemspec#L19

v5 of the `redis` gem has emerged, so this is starting to cause grief for `Gemfile`(s) that don't specify a version for the `redis` gem (eg. all Rails 6.1 `rails new` apps!)

Locking versions until major dependencies can be tested is a reasonable strategy, but v5 has been out for a while now. Are there actually any blocking changes?

**Comment by Jesterovskiy** [comment]
Hey) Good catch. Can you make PR with changes?

**Comment by leastbad** [comment]
@Jesterovskiy I prepared a PR. I don't know if it's a *great* PR - the RuboCop constraints are legitimately stifling - but all of the tests pass and it seems to work with `redis-rb` v5.0.5 in my test application.

HTH!

**Comment by leastbad** [comment]
Great news! Thanks for the merge.

Any chance you could cut a release? I can't ship the next version of StimulusReflex if this gem is broken with redis-rb 5...

**Comment by leastbad** [comment]
@Jesterovskiy just a friendly ping on potentially cutting a `0.12` release. What are the current blockers?

**Comment by aurels** [comment]
Hi,

Any reason why `0.12` isn't available on Rubygems ?
https://rubygems.org/gems/redis-session-store/versions
