### ISSUE TITLE
Bigger TTL for signed in users

### ISSUE THREAD

**Issue by kirs** [roidrage/redis-session-store#57]
For our app, we have about 2.5M session keys in redis. All of them has fixed (1 week) TTL.
I was thinking if it's a good idea to make TTL smaller for guests and bigger for signed in users.

Any thoughts?

**Comment by dmitry** [comment]
Looks like you can set expiration for every request in the middleware, before the redis session store is applied. Look for more details here: https://github.com/roidrage/redis-session-store/blob/master/lib/redis-session-store.rb#L117

**Comment by kirs** [comment]
Thanks!

**Comment by meatballhat** [comment]
@dmitry :heart:
