### ISSUE TITLE
redis-rb 3.1.0

### ISSUE THREAD

**Issue by Soliah** [roidrage/redis-session-store#58]
With the latest version of the redis ruby client doesn't seem to work with the options specified in the README. I keep on getting the following:

```
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/redis-3.1.0/lib/redis/client.rb:370:in `_parse_options': invalid url (ArgumentError)
```

Digging through the redis client source I've had to switch to using a redis URL scheme:

```
Rails.application.config.session_store :redis_session_store, {
  key: "_#{Rails.application.class.parent_name}_session_#{Rails.env}",
  redis: {
    expire_after: 7.days,
    url: "redis://localhost:6379/0"
  }
}
```

I believe this maybe because of changes to `_parse_options` in the redis client. https://github.com/redis/redis-rb/blob/7c4a95413009cefa0c74d8d320f1ae90a1c953c2/lib/redis/client.rb

**Comment by dantesolis** [comment]
:+1: Thanks @Soliah 

For others having the same problem, I got it to work with: 
```
Resque.redis = Redis.new(url: 'redis://localhost:6379/0')
Resque.after_fork = Proc.new {
	ActiveRecord::Base.establish_connection 
}
```

**Comment by meatballhat** [comment]
Sorry for the long delay, folks!  Given that this gem hands over whatever is specified in the `redis: {}` hash, I'm going to call this a documentation bug.

**Comment by meatballhat** [comment]
Should be good in master now :+1:
