### ISSUE TITLE
Adding a password to session_store.rb

### ISSUE THREAD

**Issue by chrisjeon** [roidrage/redis-session-store#59]
How do you add a password to the redis host?  I'm currently passing in a password parameter, but I don't see that in the docs.  Surprisingly, it's working, but that makes me worry a little bit.  Is password a parameter you can pass in as part of the parameter?

**Comment by dmitry** [comment]
I think this gem is nothing about the redis client. More information about the options you can pass to the redis client you can find out here: https://github.com/redis/redis-rb

**Comment by meatballhat** [comment]
@chrisjeon what @dmitry says is true :smiley:  You can create a client however you like and inject it (https://github.com/roidrage/redis-session-store/blob/47f82eed52c02b0d58a5c40113ec784e7f3a8820/lib/redis-session-store.rb#L47)
