### ISSUE TITLE
SAVE or BGSAVE?

### ISSUE THREAD

**Issue by alxx** [roidrage/redis-session-store#66]
It might be useful if there was a gem option that would cause it to issue a SAVE or a BGSAVE command to Redis. Then session (and all other data) could be recovered in case of a crash.

Example: 
`> save
`

or

`> save 60
`# saves every sixty seconds

or

`> save 60 100
`# save once a minute if at least a hundred keys have been changed

Redis persistence: http://redis.io/topics/persistence

**Comment by meatballhat** [comment]
@alxx Hey!  Can you accomplish the same by issuing the `SAVE` or `BGSAVE` commands out of band?  The idea of a session gem controlling Redis persistence doesn't feel right to me, personally, but that's just one human's opinion... :smile_cat:

**Comment by alxx** [comment]
@meatballhat Hi Dan,

Sorry, I was away on holiday :)

Sure, it's possible to control data persistence separate of session, but if all you're using Redis for is to store the session, you probably don't want to bother. (Or, perhaps, don't even have the knowledge required.) After all, if you use any other kind of session store, you certainly don't have to think what happens if the store restarts.

This gem reads and writes into Redis. What feels wrong to you about the idea that the gem itself also knows how important the data it reads and writes actually is?

The reason Redis has commands like SAVE is because it delegates judgement of the importance of data to the programmer. Session management seems to me like a pretty atomic task in web dev. Wouldn't you say that good session management would have to function even after a restart of its data store? After all, I can't think of any other session store library that doesn't...

And even if you're right, I'm not saying that the gem should by default save data; I suggested there was an option that allowed the programmer to do it via the gem. After all, the gem is already configured to speak to Redis, why would the developer have to establish some separate access into Redis (probably using another gem just for this one thing) only to send SAVE commands every now and then? (_When?_ is also a good question; the session gem can answer it, but the dev would have to improvise.)

**Comment by meatballhat** [comment]
@alxx I follow, and I'm not saying it's a bad idea.  I can't think of a sensible default for such a feature 😸   Any time I think through a given solution, I find myself effectively re-implementing the server-side config bits for save intervals.  Every default redis config I've seen (which I admit is far from all of them) has *something* in place, e.g. the `SNAPSHOTTING` section in http://download.redis.io/redis-stable/redis.conf.  I have to assume that hosted redis services are setting similar defaults.

Maybe it would help me understand what kind of data loss scenario you're trying to prevent.

**Comment by alxx** [comment]
Just whatever's in the session. Mainly shopping baskets, and logging users out, and the like.

I've honestly never used hosted Redis :) wasn't even aware someone provided this kind of thing.
Wherever I've deployed Redis there was no such default.

Let me know what you decide, and thanks :)

**Comment by meatballhat** [comment]
@alxx I should clarify that I'm not talking about what's *in* the session data, but what failure scenario you're hoping to get around.  You're saying that when you've deployed Redis there was no such default (for snapshotting, I assume?), but how are you verifying this?  Are you installing a `redis-server` binary (not package) and supplying your own `redis.conf` that explicitly disables snapshotting?  Said another way: I don't think that this gem is going to be able to do a better job than redis itself at keeping data safe if the redis server to which it's connected is at risk of crashing and losing data prior to snapshot.

**Comment by alxx** [comment]
I don't understand your first sentence :) the risk is about session data, since this is a session management gem.

I never touched the Redis defaults, but I'm certain that data didn't persist after a server crash. Why servers crash is waaay beyond the scope of this thread :)

I don't mean to argue, I just offered a suggestion that I felt would've been useful to me at that time. If you disagree, please feel free to close the issue.

Thanks!

**Comment by meatballhat** [comment]
@alxx I'm not arguing, I swear! :smile_cat:  I want to understand, and see if we can arrive at a solution that *hopefully* solves your problem without introducing too much maintenance overhead or bug vectors.  tl; dr - I think `CONFIG SET save` is the way to go, assuming you aren't shipping (or can't modify) the server config.

I think we're talking about somewhat different things.  I can say with confidence that adding some capability to this gem to perform `SAVE` periodically/event-based/other will not make the session data significantly more safe, since the `SAVE` that really matters is the one that happens right before the redis server exits.  If the redis server has been `SIGKILL`'d, then all bets are off anyway.

Here's a demonstration of how I think this *should* be solved with `CONFIG SET save "<whatever you like>"`, also showing how I was unable to get data loss even when the save settings weren't especially paranoid: https://gist.github.com/meatballhat/70aec77e9f04ff36de1829793e457528

This was a fun exercise, and really helped me understand something about redis that I'd previously taken for granted, so *thank you*!

**Comment by alxx** [comment]
@meatballhat that gist looks fine to me!

You're right that all bets are off when bombs explode, but when you're called into the office upstairs to explain why you haven't done everything possible to minimise data loss, you start to think that maybe periodic/event-based/other `SAVE`s would've been preferable. :)

Thank you!

**Comment by meatballhat** [comment]
@alxx Does that mean you're OK with doing some `CONFIG SET save` out of band, or would you want such a thing to be part of this gem? 😸

**Comment by alxx** [comment]
@meatballhat Sorry, I wasn't clear :) giving the command out of band seems satisfactory! Thanks!
