### ISSUE TITLE
Need to share session with java spring mvc

### ISSUE THREAD

**Issue by wangjingling** [roidrage/redis-session-store#78]
In our project, we need to share session between rails and spring. So I modified some code to adapt to other framework. May I pull them to this repo or build a new one?

**Comment by meatballhat** [comment]
Please feel free to create a pull request so that your changes may be reviewed.  :smile_cat:

**Comment by wangjingling** [comment]
[see the pull request please](https://github.com/roidrage/redis-session-store/pull/80)
