### ISSUE TITLE
Support rails 5.1

### ISSUE THREAD

**Issue by dmitry** [roidrage/redis-session-store#93]
Here is the patch makes redis-session-store work on rails 5.1: https://github.com/CapCap/redis-session-store/commit/ed766bcbfeda96421c3f09b49efa7a1cd4f76677

**Comment by romikoops** [comment]
Up

**Comment by nimashariatian** [comment]
any updates on this? or the PR in progress? #91

**Comment by jpawlyn** [comment]
Happy to help if there's anything that needs doing before releasing a rails 5.1 compatible gem

**Comment by Jesterovskiy** [comment]
@dmitry @nimashariatian https://github.com/roidrage/redis-session-store/pull/91 is merged. In my project works fine. Do we need other changes or I can close this issue?

**Comment by nimashariatian** [comment]
perfect, thanks @Jesterovskiy !
