### ISSUE TITLE
VERSION = '0.9.1'.freeze <- 0.9.2 ?

### ISSUE THREAD

**Issue by eric-christian** [roidrage/redis-session-store#96]
Hey,

i wanted to upgrade my project to rails 5.1 but the bundler came up with a version conflict.

Is it correct that the VERSION is still set to 0.9.1?
There is a release for 0.9.2 https://github.com/roidrage/redis-session-store/releases/tag/v0.9.2
So far i changed my Gemfile to load the gem from github. It is still shown as 0.9.1 but has all the changes for 0.9.2.

What can i do to get the 0.9.2 release from rubygems.org?
Would rubygems.org automatically update to 0.9.2 after VERSION ist set to 0.9.2?

Best regards
Eric

**Comment by Jesterovskiy** [comment]
@eric-christian I don't have rights to release on rubygems. @roidrage can you help with this?

**Comment by Jesterovskiy** [comment]
@iancanderson @meatballhat @dplummer can you help with release?

**Comment by roidrage** [comment]
@Jesterovskiy Sure can. Do you have an active account on Rubygems.org? Can add your email there as a contributor.

**Comment by Jesterovskiy** [comment]
@roidrage jester.dash@gmail.com

**Comment by roidrage** [comment]
Added you as an owner so you can now cut releases.

🎉

**Comment by Jesterovskiy** [comment]
@eric-christian released, check plz

**Comment by eric-christian** [comment]
Looks good! :)
